#############################################################################
# Makefile for building: qcompany
# Generated by qmake (2.01a) (Qt 4.8.3) on: ?r. sty 2 13:18:57 2013
# Project:  qcompany.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile qcompany.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-qfaktury \
		sub-qfaktury-tests-qfakturyTests

qfaktury//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qfaktury/ || $(MKDIR) qfaktury/ 
	cd qfaktury/ && $(QMAKE) /home/prog/varias2/opensource/qcompany/qfaktury/qfaktury.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qfaktury-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qfaktury/ || $(MKDIR) qfaktury/ 
	cd qfaktury/ && $(QMAKE) /home/prog/varias2/opensource/qcompany/qfaktury/qfaktury.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qfaktury: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE)
sub-qfaktury-make_default: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) 
sub-qfaktury-make_first: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) first
sub-qfaktury-all: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) all
sub-qfaktury-clean: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) clean
sub-qfaktury-distclean: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qfaktury-install_subtargets: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) install
sub-qfaktury-uninstall_subtargets: qfaktury//$(MAKEFILE) FORCE
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) uninstall
qfaktury/tests/qfakturyTests//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qfaktury/tests/qfakturyTests/ || $(MKDIR) qfaktury/tests/qfakturyTests/ 
	cd qfaktury/tests/qfakturyTests/ && $(QMAKE) /home/prog/varias2/opensource/qcompany/qfaktury/tests/qfakturyTests/qfakturyTests.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qfaktury-tests-qfakturyTests-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qfaktury/tests/qfakturyTests/ || $(MKDIR) qfaktury/tests/qfakturyTests/ 
	cd qfaktury/tests/qfakturyTests/ && $(QMAKE) /home/prog/varias2/opensource/qcompany/qfaktury/tests/qfakturyTests/qfakturyTests.pro -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o $(MAKEFILE)
sub-qfaktury-tests-qfakturyTests: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE)
sub-qfaktury-tests-qfakturyTests-make_default: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) 
sub-qfaktury-tests-qfakturyTests-make_first: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) first
sub-qfaktury-tests-qfakturyTests-all: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) all
sub-qfaktury-tests-qfakturyTests-clean: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) clean
sub-qfaktury-tests-qfakturyTests-distclean: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qfaktury-tests-qfakturyTests-install_subtargets: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) install
sub-qfaktury-tests-qfakturyTests-uninstall_subtargets: qfaktury/tests/qfakturyTests//$(MAKEFILE) FORCE
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qcompany.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile qcompany.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile qcompany.pro

qmake_all: sub-qfaktury-qmake_all sub-qfaktury-tests-qfakturyTests-qmake_all FORCE

make_default: sub-qfaktury-make_default sub-qfaktury-tests-qfakturyTests-make_default FORCE
make_first: sub-qfaktury-make_first sub-qfaktury-tests-qfakturyTests-make_first FORCE
all: sub-qfaktury-all sub-qfaktury-tests-qfakturyTests-all FORCE
clean: sub-qfaktury-clean sub-qfaktury-tests-qfakturyTests-clean FORCE
distclean: sub-qfaktury-distclean sub-qfaktury-tests-qfakturyTests-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-qfaktury-install_subtargets sub-qfaktury-tests-qfakturyTests-install_subtargets FORCE
uninstall_subtargets: sub-qfaktury-uninstall_subtargets sub-qfaktury-tests-qfakturyTests-uninstall_subtargets FORCE

sub-qfaktury-check: qfaktury/$(MAKEFILE)
	cd qfaktury/ && $(MAKE) -f $(MAKEFILE) check
sub-qfaktury-tests-qfakturyTests-check: qfaktury/tests/qfakturyTests/$(MAKEFILE)
	cd qfaktury/tests/qfakturyTests/ && $(MAKE) -f $(MAKEFILE) check
check: sub-qfaktury-check sub-qfaktury-tests-qfakturyTests-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

